# ruff: noqa: E501  (the snippets stay as they were measured)
"""Snippets of normal work and what the detector must answer for each (review of 2026-09-29, 679 snippets).

NO_HIT must stay silent: code, config, docs, logs and prose that carry no secret. HIT are the true positives
next to them. A `§` splits every value in HIT, so the tree scan and the pre-commit check do not take this
file for a leak; the test removes it before the scan. Every value here is made up.
"""

NO_HIT = [
    ('py env lookup', 'p§assword = os.environ["DB_P§ASSWORD"]'),
    ('py env get', 'a§pi_k§ey = os.environ.get("OPENAI_A§PI_K§EY")'),
    ('py env getenv default', 't§oken = os.getenv("GITLAB_T§OKEN", "")'),
    ('py type annot', 't§oken: str'),
    ('py type annot opt', 'a§pi_k§ey: Optional[str] = None'),
    ('py none default', 'def connect(host, a§pi_k§ey=None, s§ecret=None):'),
    ('py self attr', 's§ecret=self.s§ecret'),
    ('py self attr 2', 'self.p§assword = p§assword'),
    ('py if not continue', 'for t in t§okens:\n    if not t§oken:\n        continue'),
    ('py if not return', 'if not t§oken:\n    return None'),
    ('py if not raise', 'if not p§assword:\n    raise ValueError("p§assword required")'),
    ('py cond else', 'if p§assword:\n    ok = True\nelse:\n    ok = False'),
    ('py dict a§ccess', 'p§assword = config["database"]["p§assword"]'),
    ('py dict get', 's§ecret = settings.get("S§ECRET_KEY")'),
    ('py fstring', 'url = f"https://{user}:{p§assword}@{host}/db"'),
    ('py dataclass field', '@dataclass\nclass C§reds:\n    p§assword: str = field(repr=False)'),
    ('py pydantic', 'class Settings(BaseSettings):\n    a§pi_k§ey: S§ecretStr\n    db_p§assword: str = Field(..., env="DB_P§ASSWORD")'),
    ('py argparse', 'parser.add_argument("--p§assword", required=True, help="the database p§assword")'),
    ('py docstring', '"""Return the A§PI k§ey for the given service.\n\n    a§pi_k§ey: the k§ey to use\n    """'),
    ('py comment', '# p§assword: the value from the vault, never logged'),
    ('py logging', 'logger.info("p§assword rotated for user %s", user)'),
    ('py test fixture test123', 'def t§est_login():\n    resp = client.post("/login", data={"username": "alice", "p§assword": "test123"})'),
    ('py test fixture changeme', 'P§ASSWORD = "changeme"'),
    ('py test fixture s§ecret', 'S§ECRET = "s§ecret"'),
    ('py test fixture hunter2', 'p§assword = "hunter2"'),
    ('py test fixture p§assword123', 'assert user.check_p§assword("p§assword123")'),
    ('py test fixture p§assword1', 'p§assword="p§assword1"'),
    ('py test fixture wrongp§ass', 'client.login(username="bob", p§assword="wrongp§assword")'),
    ('py test fixture testp§ass', 'T§EST_P§ASSWORD = "testp§ass"'),
    ('py test fixture correct horse', 'p§assword = "correct horse battery staple"'),
    ('py test fixture s§ecret-k§ey-for-tests', 'S§ECRET_KEY = "not-a-real-s§ecret-k§ey-for-tests"'),
    ('py django s§ecret k§ey insecure', "S§ECRET_KEY = 'django-insecure-4^8k#p2z!q9w%x1v@r7t&y3u(o6i)e5a_s0d+f2g-h4j=k6l'"),
    ('py django settings ref', 'S§ECRET_KEY = os.environ["DJANGO_S§ECRET_KEY"]'),
    ('py mock', 'mock_get_s§ecret.return_value = "dummy"'),
    ('py pytest param', '@pytest.mark.parametrize("p§assword", ["", "short", "a" * 200])'),
    ('py kwargs', 'session = requests.Session(); session.a§uth = (user, p§assword)'),
    ('py getp§ass', 'p§assword = getp§ass.getp§ass("P§assword: ")'),
    ('py k§eyring', 'p§assword = k§eyring.get_p§assword("system", username)'),
    ('py hash', 'p§assword_hash = bcrypt.hashpw(p§assword.encode(), bcrypt.gensalt())'),
    ('py sha256 hexdigest', 'assert hashlib.sha256(b"abc").hexdigest() == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"'),
    ('py t§oken compare', 'if t§oken != expected_t§oken:\n    abort(401)'),
    ('py t§oken type check', 'if not isinstance(t§oken, str):\n    raise TypeError'),
    ('py p§assword validation', 'if len(p§assword) < 8:\n    errors.append("p§assword too short")'),
    ('py p§assword: sentence in error', 'raise ValueError("p§assword: must contain a digit")'),
    ('py json dumps', 'body = json.dumps({"p§assword": p§assword, "t§oken": t§oken})'),
    ('py dict literal refs', 'payload = {"a§pi_k§ey": a§pi_k§ey, "s§ecret": s§ecret}'),
    ('py dict literal placeholder', 'payload = {"a§pi_k§ey": "<your-a§pi-k§ey>", "s§ecret": "${S§ECRET}"}'),
    ('py dict literal xxx', 'headers = {"A§uthorization": "Bearer xxx"}'),
    ('py bearer placeholder', 'headers = {"A§uthorization": "Bearer <t§oken>"}'),
    ('py bearer fstring', 'headers = {"A§uthorization": f"Bearer {t§oken}"}'),
    ('py bearer stars', 'print("A§uthorization: Bearer ********************")'),
    ('py assert t§oken in', 'assert "t§oken" in response.json()'),
    ('py t§oken = None', 't§oken = None'),
    ('py t§oken = empty', 't§oken = ""'),
    ('py t§oken = value', 't§oken = response.json()["a§ccess_t§oken"]'),
    ('py s§ecret_name', 's§ecret_name = "prod/db/p§assword"'),
    ('py s§ecret path', 's§ecret = client.get_s§ecret(S§ecretId="prod/db/p§assword")'),
    ('py p§assword: type comment', 'p§assword: str  # the database p§assword'),
    ('py class attr', 'class User(Base):\n    p§assword_hash = Column(String(128), nullable=False)'),
    ('py enum', 'class A§uthMode(Enum):\n    P§ASSWORD = "p§assword"\n    T§OKEN = "t§oken"'),
    ('py constant names', 'P§ASSWORD_MIN_LENGTH = 12\nT§OKEN_TTL_SECONDS = 3600'),
    ('py p§assword = input', 'p§assword = input()'),
    ('py t§oken = generate', 't§oken = s§ecrets.t§oken_urlsafe(32)'),
    ('py fixture yaml-like', 'p§assword: Optional[str] = None'),
    ('py p§assword=None kw', 'conn = psycopg2.connect(host=host, user=user, p§assword=None, dbname=db)'),
    ('py s§ecret=Ellipsis', 's§ecret: bytes = ...'),
    ('py t§oken=t§oken', 'client = Client(t§oken=t§oken)'),
    ('py typing dict', 'C§redentials = TypedDict("C§redentials", {"p§assword": str, "t§oken": str})'),
    ('py test decoy', 'def t§est_p§assword_is_hashed(self):\n    self.user.set_p§assword("s3cr3t")\n    self.assertNotEqual(self.user.p§assword, "s3cr3t")'),
    ('py test 123456', 'user = User(email="a@example.com", p§assword="123456")'),
    ('py test admin', 'client.login(username="admin", p§assword="admin")'),
    ('py test letmein', 'p§assword = "letmein"'),
    ('py test P§assw0rd', 'P§ASSWORD = "P§assw0rd!"'),
    ('py test p§ass1234', 'form = {"p§assword": "p§ass1234", "p§assword_confirm": "p§ass1234"}'),
    ('py test Test1234!', 'assert validate_p§assword("Test1234!") is True'),
    ('py test t§oken = abc', 't§oken = "abc"'),
    ('py test t§oken = testt§oken', 'T§OKEN = "testt§oken"'),
    ('py test t§oken = test-t§oken', 'headers = {"A§uthorization": "Bearer test-t§oken"}'),
    ('py test t§oken fake', 'client = Client(a§pi_k§ey="fake-k§ey")'),
    ('py test a§pi_k§ey = sk-test', 'openai.a§pi_k§ey = "sk-test"'),
    ('py test s§ecret = my-s§ecret', 'app.config["S§ECRET_KEY"] = "my-s§ecret"'),
    ('py test s§ecret = dev', 'S§ECRET_KEY = "dev"'),
    ('py flask s§ecret example', "app.s§ecret_key = 'super s§ecret k§ey'"),
    ('py flask s§ecret example2', 'app.s§ecret_key = b\'_5#y2L"F4Q8z\\n\\xec]/\''),
    ('py p§assword verifying', 'return check_p§assword_hash(self.p§assword_hash, p§assword)'),
    ('ts interface', 'interface C§redentials {\n  p§assword: string;\n  t§oken?: string;\n}'),
    ('ts type union', 'type A§uthKind = "p§assword" | "t§oken";'),
    ('ts const env', 'const a§piK§ey = process.env.OPENAI_A§PI_K§EY;'),
    ('ts const env bracket', 'const t§oken = process.env["GITHUB_T§OKEN"] ?? "";'),
    ('ts object shorthand', 'const body = { username, p§assword };'),
    ('ts object prop', 'const body = { username: user, p§assword: p§ass };'),
    ('ts destructure', 'const { p§assword, t§oken } = req.body;'),
    ('ts zod', 'const schema = z.object({ p§assword: z.string().min(8), t§oken: z.string().optional() });'),
    ('ts jest', 'await request(app).post("/login").send({ email: "a@example.com", p§assword: "test123" });'),
    ('ts jest mock', 'jest.mock("./s§ecrets", () => ({ getS§ecret: () => "dummy" }));'),
    ('ts axios header', 'headers: { A§uthorization: `Bearer ${t§oken}` }'),
    ('ts axios header literal placeholder', 'headers: { A§uthorization: "Bearer YOUR_T§OKEN_HERE" }'),
    ('js require', 'const s§ecret = require("./config").s§ecret;'),
    ('js jwt sign', 'const t§oken = jwt.sign({ sub: user.id }, process.env.JWT_S§ECRET, { expiresIn: "1h" });'),
    ('js if !t§oken return', 'if (!t§oken) return res.status(401).end();'),
    ('js if !t§oken throw', 'if (!t§oken) throw new Error("t§oken missing");'),
    ('js p§assword === ', 'if (p§assword === confirmP§assword) {'),
    ('js p§assword !==', 'if (user.p§assword !== hashed) return false;'),
    ('js p§assword === literal', "if (p§assword === 'admin') {"),
    ('js localStorage', "const t§oken = localStorage.getItem('t§oken');"),
    ('js react state', "const [p§assword, setP§assword] = useState('');"),
    ('js react input', '<input type="p§assword" name="p§assword" value={p§assword} onChange={e => setP§assword(e.target.value)} />'),
    ('js i18n', '"p§assword.label": "P§assword",\n"p§assword.help": "Enter your p§assword",'),
    ('js i18n de', '"p§asswort.label": "P§asswort",\n"p§asswort.hilfe": "Bitte P§asswort eingeben",'),
    ('js console.log', "console.log('t§oken:', t§oken);"),
    ('js template literal', 'const url = `https://${user}:${p§assword}@${host}`;'),
    ('js cypress', "cy.get('#p§assword').type('P§assword123!');"),
    ('js playwright', "await page.fill('input[name=p§assword]', 's§ecret')"),
    ('js package.json', '{\n  "name": "app",\n  "version": "1.0.0",\n  "dependencies": { "lodash": "^4.17.21", "jsonwebt§oken": "^9.0.0" }\n}'),
    ('js lockfile integrity', '"integrity": "sha512-VaNbFbdhmgd6rC2sgYCd2mKA4TjFR3GAwqPrbpBWgKlkJEs4QhkeOEBwd5UgnUpk9pqbxtXvZWpKmy3w9FOeAg=="'),
    ('js lockfile resolved', '"resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",'),
    ('ts s§ecret: never', 'type Public<T> = Omit<T, "p§assword" | "s§ecret">;'),
    ('ts t§oken: T§oken', 't§oken: T§oken'),
    ('ts p§assword: P§assword', 'p§assword: P§assword'),
    ('ts class private', 'private readonly a§piK§ey: string;'),
    ('ts constructor', 'constructor(private readonly s§ecret: string) {}'),
    ('ts a§pi_k§ey = a§piK§ey', 'const config = { a§pi_k§ey: a§piK§ey, s§ecret: clientS§ecret };'),
    ('ts p§assword = undefined', 'let p§assword: string | undefined = undefined;'),
    ('ts t§oken = await', 'const t§oken = await getA§ccessT§oken();'),
    ('ts s§ecret.value', 'const value = s§ecret.value;'),
    ('ts export const', 'export const T§OKEN_K§EY = "a§uth_t§oken";'),
    ('ts graphql', 'mutation Login($p§assword: String!) { login(p§assword: $p§assword) { t§oken } }'),
    ('ts t§oken: string[]', 't§okens: string[]'),
    ('ts p§assword: z.string()', 'p§assword: z.string()'),
    ('ts t§oken: string|null', 't§oken: string | null'),
    ('ts opena§pi like', 'p§assword:\n  type: string\n  format: p§assword\n  minLength: 8'),
    ('go struct', 'type Config struct {\n\tP§assword string `json:"p§assword"`\n\tT§oken    string `json:"t§oken,omitempty"`\n}'),
    ('go env', 't§oken := os.Getenv("GITHUB_T§OKEN")'),
    ('go if t§oken empty', 'if t§oken == "" {\n\treturn errors.New("t§oken required")\n}'),
    ('go flag', 'p§assword := flag.String("p§assword", "", "database p§assword")'),
    ('go test', 'req.SetBasicA§uth("user", "p§ass")'),
    ('go test 2', 'cfg := Config{P§assword: "test123", T§oken: "testt§oken"}'),
    ('go test 3', 'cfg := Config{P§assword: "hunter2"}'),
    ('go const', 'const t§okenHeader = "X-A§uth-T§oken"'),
    ('go url userinfo', 'u := url.UserP§assword(user, p§assword)'),
    ('go err', 'return fmt.Errorf("p§assword: %w", err)'),
    ('go s§ecret = value', 's§ecret := []byte(os.Getenv("JWT_S§ECRET"))'),
    ('go struct tag yaml', 'A§PIK§ey string `yaml:"a§pi_k§ey" env:"A§PI_K§EY"`'),
    ('java field', 'private String p§assword;'),
    ('java getter', 'public String getP§assword() { return p§assword; }'),
    ('java setter', 'this.p§assword = p§assword;'),
    ('java annotation', '@Value("${db.p§assword}")\nprivate String dbP§assword;'),
    ('java props', 'String t§oken = System.getenv("A§PI_T§OKEN");'),
    ('java test', 'User u = new User("alice", "test123");'),
    ('java test 2', 'assertEquals("s§ecret", user.getP§assword());'),
    ('java equals', 'if (p§assword.equals(confirm)) {'),
    ('kotlin data class', 'data class C§redentials(val username: String, val p§assword: String)'),
    ('kotlin val', 'val t§oken: String = BuildConfig.A§PI_T§OKEN'),
    ('kotlin test', 'val c§reds = C§redentials("bob", "p§assword123")'),
    ('java spring yml', 'spring:\n  datasource:\n    p§assword: ${DB_P§ASSWORD}\n    username: app'),
    ('java props file', 'spring.datasource.p§assword=${DB_P§ASSWORD}'),
    ('rust struct', 'pub struct Config {\n    pub p§assword: String,\n    pub t§oken: Option<String>,\n}'),
    ('rust env', 'let t§oken = std::env::var("T§OKEN").expect("T§OKEN not set");'),
    ('rust match', 'let t§oken = match t§oken {\n    Some(t) => t,\n    None => return Err(anyhow!("no t§oken")),\n};'),
    ('rust test', 'let cfg = Config { p§assword: "test123".into(), t§oken: None };'),
    ('rust secrecy', 'p§assword: S§ecret<String>,'),
    ('rust clap', '#[arg(long, env = "DB_P§ASSWORD")]\np§assword: String,'),
    ('rust s§ecret_key', 'let s§ecret_key = S§ecretK§ey::generate(&mut OsRng);'),
    ('cs prop', 'public string P§assword { get; set; }'),
    ('cs config', 'var t§oken = Configuration["A§uth:T§oken"];'),
    ('cs test', 'var user = new User { Name = "a", P§assword = "test123" };'),
    ('php', "$p§assword = $_ENV['DB_P§ASSWORD'];"),
    ('php arr', "'p§assword' => env('DB_P§ASSWORD', 's§ecret'),"),
    ('php arr 2', "'p§assword' => 's§ecret',"),
    ('php test', "$this->post('/login', ['email' => 'test@example.com', 'p§assword' => 'p§assword']);"),
    ('ruby', 'p§assword = ENV.fetch("DB_P§ASSWORD")'),
    ('ruby yaml', 'p§assword: <%= ENV["DB_P§ASSWORD"] %>'),
    ('ruby test', 'user = User.create!(email: "a@example.com", p§assword: "p§assword123")'),
    ('ruby devise', 'config.pepper = ENV["DEVISE_PEPPER"]'),
    ('ruby factory', 'factory :user do\n  p§assword { "test1234" }\nend'),
    ('yaml k8s s§ecret ref', 'env:\n  - name: DB_P§ASSWORD\n    valueFrom:\n      s§ecretK§eyRef:\n        name: db-c§reds\n        k§ey: p§assword'),
    ('yaml k8s s§ecret name', 's§ecretName: my-tls-s§ecret'),
    ('yaml k8s stringData empty', 'stringData:\n  p§assword: ""'),
    ('yaml compose', 'environment:\n  - POSTGRES_P§ASSWORD=${POSTGRES_P§ASSWORD}\n  - POSTGRES_USER=app'),
    ('yaml compose literal', 'environment:\n  POSTGRES_P§ASSWORD: postgres\n  POSTGRES_USER: postgres'),
    ('yaml compose literal2', 'environment:\n  MYSQL_ROOT_P§ASSWORD: example\n  MYSQL_DATABASE: app'),
    ('yaml compose literal3', 'environment:\n  MYSQL_ROOT_P§ASSWORD: rootp§ass\n  MYSQL_DATABASE: app'),
    ('yaml gitlab ci var', 'variables:\n  DOCKER_P§ASSWORD: $CI_REGISTRY_P§ASSWORD'),
    ('yaml gitlab ci script', 'script:\n  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_P§ASSWORD" $CI_REGISTRY'),
    ('yaml gitlab ci t§oken', 'script:\n  - c§url --header "PRIVATE-T§OKEN: $GITLAB_T§OKEN" "$CI_A§PI_V4_URL/projects"'),
    ('yaml gitlab ci job t§oken', 'script:\n  - c§url --header "JOB-T§OKEN: $CI_JOB_T§OKEN" ...'),
    ('yaml gh actions', 'with:\n  t§oken: ${{ s§ecrets.GITHUB_T§OKEN }}'),
    ('yaml gh actions 2', 'env:\n  N§PM_T§OKEN: ${{ s§ecrets.N§PM_T§OKEN }}'),
    ('yaml gh actions uses', 'uses: actions/checkout@v4'),
    ('yaml gh actions uses sha', 'uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11'),
    ('yaml ansible', 'ansible_become_p§assword: "{{ vault_become_p§assword }}"'),
    ('yaml ansible vault ref', 'db_p§assword: "{{ lookup(\'env\', \'DB_P§ASSWORD\') }}"'),
    ('yaml helm values', 'a§uth:\n  p§assword: ""\n  existingS§ecret: ""'),
    ('yaml helm values 2', 'postgresql:\n  a§uth:\n    p§assword: changeme'),
    ('yaml helm values 3', 'a§uth:\n  rootP§assword: s§ecretp§assword'),
    ('yaml opena§pi', 'components:\n  securitySchemes:\n    bearerA§uth:\n      type: http\n      scheme: bearer\n      bearerFormat: JWT'),
    ('yaml opena§pi prop', 'p§assword:\n  type: string\n  format: p§assword\n  example: "P@ssw0rd"'),
    ('yaml opena§pi prop 2', 't§oken:\n  type: string\n  example: "eyJhbGciOiJIUzI1NiJ9..."'),
    ('yaml swagger example', 'example:\n  username: jdoe\n  p§assword: hunter2'),
    ('yaml mkdocs', 'site_name: Docs\nnav:\n  - Home: index.md\n  - S§ecrets: s§ecrets.md'),
    ('yaml pre-commit', 'repos:\n  - repo: https://github.com/Yelp/detect-s§ecrets\n    rev: v1.5.0\n    hooks:\n      - id: detect-s§ecrets'),
    ('yaml pre-commit args', '        args: ["--baseline", ".s§ecrets.baseline"]'),
    ('yaml dependabot', 'registries:\n  npm-github:\n    type: npm-registry\n    url: https://npm.pkg.github.com\n    t§oken: ${{s§ecrets.GH_T§OKEN}}'),
    ('json config', '{"database": {"host": "localhost", "p§assword": "", "port": 5432}}'),
    ('json schema', '{"type": "object", "properties": {"p§assword": {"type": "string", "minLength": 8}}}'),
    ('json test fixture', '{"username": "alice", "p§assword": "test123"}'),
    ('json test fixture 2', '{"username": "alice", "p§assword": "s3cr3tp§ass"}'),
    ('json vscode settings', '{"git.autofetch": true, "editor.t§okenColorCustomizations": {}}'),
    ('json tsconfig', '{"compilerOptions": {"target": "ES2022", "strict": true}}'),
    ('json mcp', '{"mcpServers": {"gw": {"type": "http", "url": "https://gw.example.com/mcp", "headers": {"A§uthorization": "Bearer ${GW_T§OKEN}"}}}}'),
    ('json s§ecrets baseline', '{"filename": "config.py", "hashed_s§ecret": "b2ee4e4b4e7f2a9b2c1d3e4f5a6b7c8d9e0f1a2b", "line_number": 12, "type": "S§ecret K§eyword"}'),
    ('json a§pi resp', '{"a§ccess_t§oken": "<redacted>", "t§oken_type": "bearer", "expires_in": 3600}'),
    ('json a§pi resp 2', '{"t§oken_type": "Bearer", "expires_in": 3600, "scope": "read write"}'),
    ('json uuid', '{"id": "3f2504e0-4f89-11d3-9a0c-0305e82c3301", "s§ecret_id": "8e4f2a1b-1c2d-4e5f-8a9b-0c1d2e3f4a5b"}'),
    ('toml pyproject', '[project]\nname = "app"\nversion = "1.2.3"\ndependencies = ["requests>=2.31"]'),
    ('toml cargo', '[dependencies]\nsecrecy = "0.8"\ntokio = { version = "1", features = ["full"] }'),
    ('toml config', '[database]\np§assword = "${DB_P§ASSWORD}"\nhost = "localhost"'),
    ('toml cargo lock', '[[package]]\nname = "syn"\nversion = "2.0.48"\nchecksum = "0f3531638e407dfc0d761b64d0d5d4f6d1de9d1f5b8b6b3c6f1c2b4c0b6a7e2e"'),
    ('toml poetry lock', '[[package]]\nname = "requests"\nversion = "2.31.0"\nfiles = [{file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f"}]'),
    ('env example', 'DB_P§ASSWORD=\nA§PI_K§EY=\nS§ECRET_KEY='),
    ('env example 2', 'DB_P§ASSWORD=your-p§assword-here\nA§PI_K§EY=your-a§pi-k§ey'),
    ('env example 3', 'DB_P§ASSWORD=changeme\nJWT_S§ECRET=changeme'),
    ('env example 4', 'DB_P§ASSWORD=<your database p§assword>\nA§PI_K§EY=<k§ey>'),
    ('env example 5', 'DB_P§ASSWORD=xxx\nA§PI_K§EY=xxxxxxxxxxxx'),
    ('env example 7', 'S§ECRET_KEY=replace-me\nDEBUG=true'),
    ('env example 8', 'S§ECRET_KEY=dev-s§ecret-k§ey\nDEBUG=true'),
    ('env example 9', 'A§PI_T§OKEN=todo'),
    ('env local dev', 'DATABASE_URL=postgres://app:app@localhost:5432/app'),
    ('env local dev 2', 'DATABASE_URL=postgres://postgres:postgres@localhost:5432/app'),
    ('env local dev 3', 'REDIS_URL=redis://:p§assword@localhost:6379/0'),
    ('env local dev 4', 'DATABASE_URL=mysql://root:root@db:3306/app'),
    ('dockerfile', 'FROM python:3.12-slim\nENV DB_P§ASSWORD=""\nARG N§PM_T§OKEN\nRUN npm ci'),
    ('dockerfile 2', 'ARG GITHUB_T§OKEN\nRUN --mount=type=s§ecret,id=npmrc npm ci'),
    ('dockerfile 3', 'ENV POSTGRES_P§ASSWORD=postgres'),
    ('shell export', 'export GITLAB_T§OKEN=$(cat ~/.gitlab-t§oken)'),
    ('shell read', 'read -s -p "P§assword: " p§assword\necho'),
    ('shell if', 'if [ -z "$T§OKEN" ]; then\n  echo "T§OKEN not set" >&2\n  exit 1\nfi'),
    ('shell c§url var', 'c§url -H "A§uthorization: Bearer $T§OKEN" https://a§pi.example.com/v1'),
    ('shell c§url var braces', 'c§url -H "A§uthorization: Bearer ${T§OKEN}" https://a§pi.example.com/v1'),
    ('shell c§url -u', 'c§url -u "$USER:$P§ASS" https://a§pi.example.com'),
    ('shell c§url -u literal', 'c§url -u admin:admin http://localhost:8080/a§pi'),
    ('shell c§url basic placeholder', 'c§url -H "A§uthorization: Basic <base64 user:p§ass>" ...'),
    ('shell docker login', 'echo "$CI_REGISTRY_P§ASSWORD" | docker login -u "$CI_REGISTRY_USER" --p§assword-stdin'),
    ('shell mysql', 'mysql -u root -p"$MYSQL_ROOT_P§ASSWORD" app'),
    ('shell psql', 'PGP§ASSWORD=$DB_P§ASSWORD psql -h localhost -U app'),
    ('shell ssh-k§eygen', 'ssh-k§eygen -t ed25519 -C "ci@example.com" -f ~/.ssh/id_ed25519 -N ""'),
    ('shell openssl', 'openssl rand -hex 32 > s§ecret.k§ey'),
    ('shell vault', 'vault kv get -field=p§assword s§ecret/prod/db'),
    ('shell aws', 'aws s§ecretsmanager get-s§ecret-value --s§ecret-id prod/db/p§assword'),
    ('shell gcloud', 'gcloud s§ecrets versions a§ccess latest --s§ecret=db-p§assword'),
    ('shell kubectl', 'kubectl create s§ecret generic db-c§reds --from-literal=p§assword="$DB_P§ASSWORD"'),
    ('shell kubectl literal', 'kubectl create s§ecret generic db-c§reds --from-literal=p§assword=test123'),
    ('shell git remote', 'git remote add origin ssh://git@gitlab.example.com:8022/devs/repo.git'),
    ('shell git log', 'commit 4f2a9c1e7b3d5f6a8c9e0b1d2f3a4c5e6d7f8a9b\nA§uthor: Dev <dev@example.com>\nDate:   Mon Sep 29 10:00:00 2026 +0200'),
    ('shell sha256sum', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file.txt'),
    ('shell md5', 'd41d8cd98f00b204e9800998ecf8427e  file.txt'),
    ('shell history t§oken flag', 'gh a§uth login --with-t§oken < t§oken.txt'),
    ('shell gh s§ecret set', 'gh s§ecret set N§PM_T§OKEN < t§oken.txt'),
    ('shell npm config', 'npm config set //registry.npmjs.org/:_a§uthT§oken=${N§PM_T§OKEN}'),
    ('shell npmrc example', '//registry.npmjs.org/:_a§uthT§oken=${N§PM_T§OKEN}'),
    ('shell pip index', 'pip install --index-url https://__t§oken__:${PYPI_T§OKEN}@pypi.example.com/simple'),
    ('shell docker run env', 'docker run -e POSTGRES_P§ASSWORD=postgres -p 5432:5432 postgres:16'),
    ('shell docker run env 2', 'docker run -e MYSQL_ROOT_P§ASSWORD=my-s§ecret-pw -d mysql:8'),
    ('shell 1p§assword', 'op read "op://Private/GitLab/t§oken"'),
    ('shell p§ass', 'p§ass show work/gitlab/t§oken | head -1'),
    ('md readme env', 'Set `DB_P§ASSWORD` in your environment before running the server.'),
    ('md readme t§oken', 'Create a personal a§ccess t§oken with the `a§pi` scope and export it as `GITLAB_T§OKEN`.'),
    ('md readme placeholder', 'Replace `<your-t§oken>` with the t§oken from the settings page.'),
    ('md readme placeholder 2', 'Run `c§url -H "A§uthorization: Bearer <T§OKEN>" https://a§pi.example.com`.'),
    ('md readme placeholder 3', '```\nexport A§PI_K§EY=your_a§pi_k§ey_here\n```'),
    ('md readme placeholder 4', '```\nexport A§PI_K§EY=sk-...\n```'),
    ('md readme placeholder 5', 'A§PI k§ey: `xxxxxxxxxxxxxxxxxxxxxxxx`'),
    ('md readme placeholder 6', 'P§assword: ********'),
    ('md readme placeholder 7', 'T§oken: `${GITLAB_T§OKEN}`'),
    ('md table', '| Variable | Description |\n|---|---|\n| `DB_P§ASSWORD` | The database p§assword |\n| `A§PI_T§OKEN` | T§oken for the A§PI |'),
    ('md table 2', '| p§assword | string | yes | The user p§assword |'),
    ('md list', '- p§assword: the user p§assword (min 8 chars)\n- t§oken: optional A§PI t§oken'),
    ('md heading', '## P§assword reset\n\nThe user requests a p§assword reset by e-mail.'),
    ('md prose s§ecret', 'The s§ecret is stored in the vault and never logged.'),
    ('md prose t§oken', 'The t§oken expires after one hour; the client must refresh it.'),
    ('md prose p§assword', 'The p§assword must be at least 12 characters long.'),
    ('md prose pw hint', 'P§assword: at least 12 characters, one digit.'),
    ('md prose colon', 'P§assword: see the wiki page "Deploy c§redentials".'),
    ('md prose colon 2', 'T§oken: the one from the CI settings, `CI_DEPLOY_T§OKEN`.'),
    ('md prose k§ey', 'The k§ey: the deploy k§ey of the runner, see docs/runner.md.'),
    ('md changelog', '## 0.5.14\n- fix(detect): `if not t§oken: continue` no longer stores the k§eyword'),
    ('md changelog 2', '- security: the p§assword was logged in debug mode (#123)'),
    ('md adr', 'Decision: store the s§ecret in the k§eychain; the t§oken is never written to disk.'),
    ('md issue', 'Steps to reproduce:\n1. Set p§assword: test123\n2. Log in\n3. Observe the error'),
    ('md issue 2', 'Expected: the p§assword field is masked.\nActual: the p§assword is shown as plain text.'),
    ('md pr desc', 'This MR renames `s§ecret` to `c§redential` in the config loader.'),
    ('md pr desc 2', 'Closes #42. The t§oken: header is now parsed case-insensitively.'),
    ('md code span', 'Use `p§assword=` on the command line, or `--p§assword-file`.'),
    ('md j§ira', 'PBE-3403: p6p trusts the X-USERID header as identity'),
    ('md s§ecret word', 'Top s§ecret: the release date is Friday.'),
    ('md k§ey word', 'The k§ey: keep it simple.'),
    ('md k§ey word 2', 'K§ey: performance, not features.'),
    ('md p§ass word', 'P§ass: the test p§assed on the second run.'),
    ('md t§oken word', 'T§oken: a lexer t§oken, not a c§redential.'),
    ('de prose 1', 'Das P§asswort muss mindestens 12 Zeichen lang sein.'),
    ('de prose 2', 'P§asswort: siehe Wiki-Seite "Z§ugangsdaten Deploy".'),
    ('de prose 4', 'Bitte das P§asswort zurücksetzen und den Nutzer informieren.'),
    ('de prose 5', 'Der S§chlüssel: die Deploy-K§ey des Runners, siehe docs/runner.md.'),
    ('de prose 6', 'S§chlüssel: Performance, nicht Features.'),
    ('de prose 7', 'G§eheimnis: Der Releasetermin ist Freitag.'),
    ('de prose 8', 'K§ennwort: bitte beim Admin erfragen.'),
    ('de prose 9', 'Z§ugangsdaten: im P§asswortmanager unter "Deploy".'),
    ('de prose 10', 'P§asswort vergessen? Klicke auf "P§asswort zurücksetzen".'),
    ('de prose 11', 'Das K§ennwort wird beim ersten Login geändert.'),
    ('de prose 12', 'Der A§PI-S§chlüssel wird aus der Umgebungsvariable gelesen.'),
    ('de prose 13', 'S§chlüssel: a§piK§ey'),
    ('de prose 14', 'P§asswort: Testp§asswort'),
    ('de prose 15', 'P§asswort: test1234'),
    ('de prose 16', 'P§asswort: g§eheim123'),
    ('de prose 17', 'Tor: Ein S§chlüssel für die Tür liegt beim Nachbarn.'),
    ('de prose 18', 'Ich brauche den S§chlüssel: Zimmer 12.'),
    ('de prose 19', 'Das P§asswort: 12 Zeichen'),
    ('de prose 22', 'Z§ugangsdaten:\nBenutzer: max\nP§asswort: hunter2'),
    ('de prose 24', 'G§eheimnis: Der Client sendet das T§oken nie an Dritte.'),
    ('de compound', 'P§asswortlänge: 12\nT§okenlaufzeit: 3600'),
    ('de tel', 'Rufen Sie an unter 030 12345678.'),
    ('de date', 'Am 29.09.2026 um 10:00 Uhr.'),
    ('de version', 'Version 2.1.284 vom 29.09.2026'),
    ('de order no', 'Bestellnummer: 4000123456789'),
    ('log http', '2026-09-29T10:00:00Z INFO GET /a§pi/users 200 12ms'),
    ('log a§uth fail', '2026-09-29T10:00:00Z WARN a§uth failed for user alice: bad p§assword'),
    ('log a§uth fail 2', 'ERROR: p§assword a§uthentication failed for user "postgres"'),
    ('log t§oken expired', '2026-09-29 10:00:00 WARN t§oken expired, refreshing'),
    ('log t§oken invalid', 'jwt: t§oken is malformed: t§oken contains an invalid number of segments'),
    ('log k8s', 'Warning  FailedMount  s§ecret "db-c§reds" not found'),
    ('log k8s 2', 'MountVolume.SetUp failed for volume "t§oken" : s§ecret "sa-t§oken" not found'),
    ('log request id', 'request_id=3f2504e0-4f89-11d3-9a0c-0305e82c3301 status=500'),
    ('log trace id', 'trace_id=4bf92f3577b34da6a3ce929d0e0e4736 span_id=00f067aa0ba902b7'),
    ('log docker pull', 'Digest: sha256:8a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f9'),
    ('log git', '[main 4f2a9c1] fix(detect): k§eyword rule\n 1 file changed, 2 insertions(+)'),
    ('log pip', 'Successfully installed requests-2.31.0 urllib3-2.2.1'),
    ('log npm', 'added 1234 packages, and audited 1235 packages in 12s'),
    ('log stack', 'Traceback (most recent call last):\n  File "app.py", line 12, in <module>\n    t§oken = get_t§oken()\nK§eyError: \'t§oken\''),
    ('log stack 2', "K§eyError: 'p§assword'"),
    ('log env dump', 'DB_P§ASSWORD=***\nA§PI_K§EY=[REDACTED]\nT§OKEN=<hidden>'),
    ('log sqlalchemy', 'Engine(postgresql://app:***@localhost/app)'),
    ('log ip private', 'Connecting to 192.168.1.10:5432'),
    ('log ip public', 'Connecting to 8.8.8.8:53'),
    ('log ip localhost', 'Listening on 127.0.0.1:8000'),
    ('log ip 0.0.0.0', 'Listening on 0.0.0.0:8000'),
    ('log ipv6', 'Listening on [::1]:8000'),
    ('log user agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15'),
    ('log timestamp epoch', 'ts=1759140000 level=info msg="ok"'),
    ('log slack channel', 'posted to C01234ABCDE thread 1759140000.123456'),
    ('log session id', 'session_id=session_01HtytMhXicLAA9DC9wEvoJA'),
    ('log tool use id', 'tool_use_id=toolu_01AgentReportTest'),
    ('diff 1', 'diff --git a/config.py b/config.py\nindex 3f2a9c1..4b5c6d7 100644\n--- a/config.py\n+++ b/config.py\n@@ -1,3 +1,3 @@\n-p§assword = os.environ["DB_P§ASSWORD"]\n+p§assword = os.environ.get("DB_P§ASSWORD", "")'),
    ('diff 2', '+    t§oken: str = ""\n-    t§oken: Optional[str] = None'),
    ('diff 3', '+P§ASSWORD = "test123"\n-P§ASSWORD = "changeme"'),
    ('diff 4', '+P§ASSWORD = "testp§ass1"'),
    ('diff 5', 'index 3f2a9c1e7b3d5f6a8c9e0b1d2f3a4c5e6d7f8a9b..4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c 100644'),
    ('diff 6', '-  s§ecret: {{ .Values.s§ecret }}\n+  s§ecret: {{ .Values.a§uth.s§ecret }}'),
    ('uuid', '3f2504e0-4f89-11d3-9a0c-0305e82c3301'),
    ('git sha', '4f2a9c1e7b3d5f6a8c9e0b1d2f3a4c5e6d7f8a9b'),
    ('sha256', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'),
    ('base64 image', '<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAE§AAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==">'),
    ('css colour', '.btn { color: #ff8800; background: #1e1e2e; border-color: #abcdef; }'),
    ('css colour 8', 'background: #1e1e2eff;'),
    ('phone de', 'Tel: 030 12345678'),
    ('version pin', 'python@3.12/3.12.7'),
    ('semver range', '"node": ">=18.0.0 <21"'),
    ('mac addr', '00:1A:2B:3C:4D:5E'),
    ('card test visa', '4111 1111 1111 1111'),
    ('card test stripe', '4242424242424242'),
    ('iban placeholder', 'DE00 0000 0000 0000 0000 00'),
    ('ipv4 doc', 'Example: 203.0.113.42'),
    ('ipv4 test-net', '198.51.100.7'),
    ('ipv4 cidr', '10.0.0.0/8 and 172.16.0.0/12'),
    ('cidr public', '203.0.113.0/24'),
    ('aws account', 'arn:aws:iam::123456789012:role/deploy'),
    ('aws example k§ey doc', 'A§KIAIOSFODNN7EXAMPLE'),
    ('aws example s§ecret doc', 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEK§EY'),
    ('aws example pair', 'AWS_A§CCESS_K§EY_ID=A§KIAIOSFODNN7EXAMPLE\nAWS_S§ECRET_A§CCESS_K§EY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEK§EY'),
    ('slack channel', 'C01234ABCDE'),
    ('hex colour list', '#123456 #abcdef #0f0f0f'),
    ('hash lockfile yarn', 'integrity sha512-Ku3M4dU7Ho6Qq4d0jDrx1xJyQzJb4d4Wf1J0vTz5W4jT6h5fJ7q8Y2b9wKt6eXgQd0wN6b7Dx2Xu8Bxn7T0qA=='),
    ('email example.com', 'Contact: support@example.com'),
    ('email example.org', 'user@example.org'),
    ('email noreply', 'From: noreply@github.com'),
    ('email localhost', 'root@localhost'),
    ('email git ssh', 'git@github.com:org/repo.git'),
    ('email doc placeholder 4', 'john.doe@example.com'),
    ('email codeowner', '* @org/team-backend'),
    ('email scoped npm', '@types/node@20.11.5'),
    ('email decorators', '@app.route("/login")\n@login_required'),
    ('email at mention', '@alice can you review?'),
    ('email at mention 2', 'cc @bob.smith'),
    ('bearer word', 'The Bearer of this t§oken may read.'),
    ('bearer word 2', 'A§uthorization: Bearer scheme is used.'),
    ('bearer placeholder brace', 'A§uthorization: Bearer {{t§oken}}'),
    ('basic placeholder', 'A§uthorization: Basic base64(user:p§assword)'),
    ('basic word', 'Basic a§uthentication is used.'),
    ('fx 1', 'p§assword = "supers§ecret"'),
    ('fx 2', 'p§assword = "SuperS§ecret1"'),
    ('fx 3', 'p§assword = "s§ecret123"'),
    ('fx 4', 'p§assword = "myp§assword"'),
    ('fx 5', 'p§assword = "testing123"'),
    ('fx 7', 'p§assword = "P@ssword"'),
    ('fx 9', 'p§assword = "foobar"'),
    ('fx 11', 'p§assword = "Str0ngP§assw0rd!"'),
    ('fx 13', 'p§assword = "wrong"'),
    ('fx 14', 'p§assword = "wrong-p§assword"'),
    ('fx 15', 'p§assword = "invalid_p§assword"'),
    ('fx 16', 'p§assword = "new_p§assword"'),
    ('fx 17', 'p§assword = "old_p§assword"'),
    ('fx 18', 'p§assword = "newp§assword1"'),
    ('fx 19', 'p§assword = "toolong" * 100'),
    ('fx 20', 'p§assword = "12345678"'),
    ('fx 21', 'p§assword = "aaaaaaaa"'),
    ('fx 23', 't§oken = "invalid"'),
    ('fx 24', 't§oken = "expired-t§oken"'),
    ('fx 25', 't§oken = "not-a-t§oken"'),
    ('fx 29', 't§oken = "tok_t§est_123"'),
    ('fx 30', 'a§pi_k§ey = "test"'),
    ('fx 31', 'a§pi_k§ey = "TESTK§EY123"'),
    ('fx 32', 's§ecret = "shhh"'),
    ('fx 33', 's§ecret = "s3cr3t"'),
    ('fx 34', 's§ecret = "tops§ecret"'),
    ('fx 35', 's§ecret = "my-s§ecret-1"'),
    ('fx 36', 'client_s§ecret = "client-s§ecret"'),
    ('fx 37', 'client_s§ecret = "cs_t§est_123"'),
    ('fx 38', 'private_k§ey = "-§----BEGIN PRIVATE K§EY-----\\n...\\n-----END PRIVATE K§EY-----"'),
    ('fx 39', 'p§assword="s§ecretp§assword"'),
    ('fx 40', 'p§wd = "s§ecret1"'),
    ('fx 43', 'P§ASSWORD: str = "hunter22"'),
    ('fx 50', 'p§assword: test123'),
    ('fx 51', 'p§assword:test123'),
    ('fx 52', 'p§assword: Test1234'),
    ('fx 53', 'p§assword: 123456'),
    ('fx 54', 'p§assword = 123456'),
    ('fx 55', 'p§ass = "p§ass"'),
    ('fx 56', 'p§ass: "p§assp§ass"'),
    ('fx 58', 'p§assword: hunter2'),
    ('ref 1', 'p§assword = settings.DATABASE_P§ASSWORD'),
    ('ref 2', 'p§assword = self._p§assword'),
    ('ref 3', 'p§assword = config.db.p§assword'),
    ('ref 4', 'p§assword = c§reds["p§assword"]'),
    ('ref 5', 'p§assword = args.p§assword'),
    ('ref 6', 'p§assword = P§ASSWORD_DEFAULT'),
    ('ref 7', 'p§assword = DEFAULT_P§ASSWORD'),
    ('ref 8', 'p§assword = p§assword_or_none'),
    ('ref 9', 't§oken = t§oken_from_header'),
    ('ref 10', 't§oken = header.split()[1]'),
    ('ref 11', 't§oken = parts[1]'),
    ('ref 12', 't§oken = cached_t§oken'),
    ('ref 13', 't§oken = T§OKEN'),
    ('ref 14', 't§oken = t§okenValue'),
    ('ref 15', 't§oken = a§ccess_t§oken'),
    ('ref 16', 't§oken = a§ccessT§oken'),
    ('ref 17', 't§oken = user.t§oken'),
    ('ref 18', 't§oken = maybe_t§oken or fallback_t§oken'),
    ('ref 19', 't§oken = t§okens[0]'),
    ('ref 20', 's§ecret = s§ecret_bytes.hex()'),
    ('ref 21', 's§ecret = base64.b64decode(raw)'),
    ('ref 22', 's§ecret = S§ECRET_VALUE'),
    ('ref 23', 's§ecret = s§ecretValue'),
    ('ref 24', 's§ecret = os.urandom(32)'),
    ('ref 25', 'a§pi_k§ey = a§pi_k§ey or DEFAULT_K§EY'),
    ('ref 26', 'a§pi_k§ey = a§pi_k§ey.strip()'),
    ('ref 27', 'a§pi_k§ey = a§pik§ey'),
    ('ref 28', 'a§pi_k§ey = k§ey'),
    ('ref 29', 'a§pi_k§ey = k§eyfile.read().strip()'),
    ('ref 30', 'p§assword = p§assword.strip()'),
    ('ref 31', 'p§assword = p§assword or ""'),
    ('ref 32', 'p§assword = p§asswd'),
    ('ref 33', 'p§assword = pw'),
    ('ref 34', 'p§assword = None if not pw else pw'),
    ('ref 35', 'p§assword = hashed'),
    ('ref 36', 'p§assword = generate_p§assword()'),
    ('ref 37', 'p§assword = get_p§assword'),
    ('ref 38', 'p§assword = getP§assword'),
    ('ref 39', 'p§assword = user_p§assword'),
    ('ref 40', 'p§assword = userP§assword'),
    ('ref 42', 'p§assword = plainte§xt_p§assword'),
    ('ref 43', 'p§assword = value'),
    ('ref 44', 'p§assword = data'),
    ('ref 45', 'p§assword = raw'),
    ('ref 46', 'p§assword = entered'),
    ('ref 48', 'p§assword = new_value'),
    ('ref 49', 'p§assword = newValue'),
    ('ref 51', 'p§assword = kwargs'),
    ('ref 52', 'p§assword = request'),
    ('ref 53', 'p§assword = unquote'),
    ('ref 55', 'p§assword = redacted'),
    ('ref 56', 'p§assword = masked_value'),
    ('ref 58', 'p§assword = MISSING'),
    ('ref 59', 'p§assword = Undefined'),
    ('ref 60', 'p§assword = NotSet'),
    ('ref 63', 'p§assword = os.environ'),
    ('ref 64', 'p§assword = environ'),
    ('ref 65', 't§oken = t§okenizer'),
    ('ref 66', 't§oken = t§okenize'),
    ('ref 67', 't§oken = nextt§oken'),
    ('ref 69', 't§oken = current'),
    ('ref 73', 't§oken = EOF'),
    ('ref 74', 't§oken = NEWLINE'),
    ('ref 75', 't§oken = INDENT'),
    ('ref 76', 't§oken = DEDENT'),
    ('ref 79', 't§oken = "NEWLINE"'),
    ('col 2', 'p§assword: hashed'),
    ('col 3', 'p§assword: required'),
    ('col 4', 'p§assword: optional'),
    ('col 6', 'p§assword: redacted'),
    ('col 7', 'p§assword: p§assword'),
    ('col 8', 'p§assword: invalid'),
    ('col 9', 'p§assword: incorrect'),
    ('col 10', 'p§assword: mismatch'),
    ('col 11', 'p§assword: expired'),
    ('col 12', 'p§assword: rotated'),
    ('col 13', 'p§assword: unknown'),
    ('col 16', 'p§assword: bcrypt'),
    ('col 18', 'p§assword: sha256'),
    ('col 19', 't§oken: expired'),
    ('col 20', 't§oken: invalid'),
    ('col 22', 't§oken: missing'),
    ('col 23', 't§oken: revoked'),
    ('col 28', 't§oken: k§eyword'),
    ('col 31', 's§ecret: rotated'),
    ('col 32', 's§ecret: required'),
    ('col 33', 'a§pi_k§ey: required'),
    ('col 34', 'a§pi_k§ey: rotated'),
    ('col 35', 'a§pi_k§ey: revoked'),
    ('col 38', 'p§assword: verys§ecret'),
    ('col 39', 'p§assword: very-s§ecret'),
    ('col 40', 'p§assword: notsos§ecret'),
    ('col 55', 'G§eheimnis: keines'),
    ('crlf continue', 'for t in ts:\r\n    if not t§oken:\r\n        continue\r\n'),
    ('8char settings', 'p§assword=settings'),
    ('8char disabled', 'p§assword=disabled'),
    ('8char optional', 't§oken=optional'),
    ('8char nullable', 's§ecret=nullable'),
    ('7char string glued', 'p§assword:string'),
    ('9char undefined', 'p§assword=undefined'),
    ('p§assword123 eq', 'p§assword = "p§assword123"'),
    ('A§KIA TP', 'A§KIAQ7W8E9R0T1Y2U3I4'),
    ('yaml s§ecret name', 's§ecretName: db-c§redentials-prod'),
    ('k8s s§ecret ref k§ey', 's§ecretK§eyRef:\n  name: db-c§reds\n  k§ey: p§assword'),
    ('terraform var', 'p§assword = var.db_p§assword'),
    ('terraform random', 'p§assword = random_p§assword.db.result'),
    ('email example.net', 'a@example.net'),
    ('email .test', 'a@foo.test'),
    ('email .invalid', 'a@foo.invalid'),
    ('email .localhost', 'a@app.localhost'),
    ('email admin@example.com', 'admin@example.com'),
    ('ip 1.1.1.1', 'dns 1.1.1.1'),
    ('ip 192.0.2.1', '192.0.2.1'),
    ('md env table', '| `DB_P§ASSWORD` | yes | `postgres` |'),
    ('compose healthcheck', 'test: ["CMD-SHELL", "pg_isready -U postgres"]'),
    ('sql', "CREATE USER app WITH P§ASSWORD 'app_p§assword';"),
    ('sql2', "ALTER USER postgres WITH P§ASSWORD 'postgres';"),
    ('ansible vault header', '$ANSIBLE_VAULT;1.1;AES256\n66386439653236336462626566653063336164663966303231363934653561363064363833313662'),
    ('git c§redential helper', 'git config c§redential.helper osxk§eychain'),
    ('http header docs', 'X-A§pi-K§ey: <a§pi-k§ey>'),
    ('http header stars', 'X-A§pi-K§ey: ****************'),
    ('http header req log', 'A§uthorization: Bearer [FILTERED]'),
    ('otp', 'Your verification code is 482913'),
    ('hunter2 sentence', 'the p§assword is hunter2 and the user is max'),
    ('german sentence', 'Das P§asswort ist Sommer2026! und der Nutzer ist max'),
    ('t§oken: sentence lower', 't§oken: expires after one hour'),
    ('s§ecret: sentence lower', 's§ecret: rotated every 90 days'),
    ('a§pi_k§ey: sentence lower', 'a§pi_k§ey: required for every call'),
    ('value camel long', 'p§assword = correctHorseBatteryStaple'),
    ('k§ey: header value', 'k§ey: value'),
    ('k§ey: id', 'k§ey: 3f2504e0-4f89-11d3-9a0c-0305e82c3301'),
    ('s§ecret_id uuid', 's§ecret_id: 3f2504e0-4f89-11d3-9a0c-0305e82c3301'),
    ('client_s§ecret uuid', 'client_s§ecret: 3f2504e0-4f89-11d3-9a0c-0305e82c3301'),
    ('aig version pin', 't§okenizers==0.20.3\n'),
    ('aig version pin renovate', '"matchPackageNames": ["t§okenizers==0.20.3"]'),
    ('aig ttl constant', 'TTL_REFRESH_T§OKEN = 15552000               # 180 days (refresh t§okens)\n'),
    ('aig ttl constant 2', 'x = 1\nTTL_CHATGPT_REFRESH_T§OKEN = 15552000       # 180 days\n'),
    ('aig max age', 'SESSION_T§OKEN_MAX_AGE = 86400000\n'),
    ('aig template doc', '    - MCP t§okens: `mcp_{user}`\n'),
    ('aig chatgpt template in docs', '    - ChatGPT t§oken: `chatgpt_a§ccess_t§oken:{hash}`\n'),
    ('aig url template', 'url = f"/transfer/{tid}/download?t§oken={body[\'transfer_id\']}"\n'),
    ('aig url template 2', 'redirect(f"/a§uth/slack/auto-connect?t§oken={SLACK_AUTO_T§OKEN}")\n'),
    ('aig private name', '    security_t§oken_cleanup = _cleanup_t§okens\n'),
    ('aig subscript type', '    gateway_t§okens: list[str]\n'),
    ('aig subscript type 2', '    s§ecrets: Dict[str, str]\n'),
    ('aig number sep', '      "estimated_t§okens": 1_234_567,\n'),
    ('aig glob', '    match="chatgpt_a§ccess_t§oken:*"\n'),
    ('aig header value', 'headers: {X-A§tlassian-T§oken: no-check}\n'),
    ('aig bearer words', 'headers = {"A§uthorization": "Bearer test-a§ccess-t§oken"}\n'),
    ('aig rfc section', '    """RFC 6749 4.1.2.1: the error is sent back to the client."""\n'),
    ('aig oidc section', '# OIDC Core 3.1.2.1 says the nonce is kept\n'),
    ('aig placeholder t§oken', 'planted = "g§lpat-" + "AAAAAAAAAAAAAAAAAAAA"\n'),
    ('aig example mail', 'Contact: support@example.com\n'),
    ('aig example mail sub', 'git config user.email ci@build.example.org\n'),
    ('aig local mail', 'sender = alerts@nas.local\n'),
]

HIT = [
    ('de kfz', 'Das Auto hat das Kennzeichen B-§AB§ 1§23§4.', [('DE_KFZ', 'B-§AB§ 1§23§4')]),
    ('de plz', 'Die Adresse ist Musterstraße 1, 10§11§5 Berlin.', [('DE_PLZ', '10§11§5')]),
    ('de tel intl', 'Rufen Sie an unter +4§9 §30§ 1§23§45§67§8.', [('PHONE', '+4§9 §30§ 1§23§45§67§8')]),
    ('de iban', 'IBAN: DE§89§ 3§70§4 §00§44§ 0§53§2 §01§30§ 0§0', [('IBAN', 'DE§89§ 3§70§4 §00§44§ 0§53§2 §01§30§ 0§0')]),
    ('de steuer', 'Steuernummer: 12§/3§45§/6§78§90', [('DE_TAX_NUMBER', '12§/3§45§/6§78§90')]),
    ('phone intl', '+4§9 §30§ 1§23§45§67§8', [('PHONE', '+4§9 §30§ 1§23§45§67§8')]),
    ('phone intl 2', '+1§ (§55§5)§ 1§23§-4§56§7', [('PHONE', '+1§ (§55§5)§ 1§23§-4§56§7')]),
    ('iban example', 'DE§89§37§04§00§44§05§32§01§30§00', [('IBAN', 'DE§89§37§04§00§44§05§32§01§30§00')]),
    ('random letters 10', 'p§assword: xk§qv§bt§rz§pl', [('SECRET', 'xk§qv§bt§rz§pl')]),
    ('random letters 14', 't§oken = "qz§jx§vb§wm§kp§lr§ty"', [('SECRET', 'qz§jx§vb§wm§kp§lr§ty')]),
    ('word Sommerzeit2026!', 'p§assword: So§mm§er§ze§it§20§26§!', [('SECRET', 'So§mm§er§ze§it§20§26§!')]),
    ('two letters TP', 'p§assword: as§as§as§as§as§as§as', [('SECRET', 'as§as§as§as§as§as§as')]),
    ('mixed TP', 'p§assword: Kx§7Q§p2§Zr§9L§m4§Wn', [('SECRET', 'Kx§7Q§p2§Zr§9L§m4§Wn')]),
    ('special TP', 'p§assword: a!§b#§c$§d%§e&§f*§g+§h-§i_§j@§k!', [('SECRET', 'a!§b#§c$§d%§e&§f*§g+§h-§i_§j@§k!')]),
    ('glpat TP', 't§oken: gl§pa§t-§Q7§w8§E9§r0§T1§y2§U3§i4§O5§p6', [('SECRET', 'gl§pa§t-§Q7§w8§E9§r0§T1§y2§U3§i4§O5§p6')]),
    ('ghp TP', 'gh§p_§Q7§w8§E9§r0§T1§y2§U3§i4§O5§p6§Q7§w8§E9§r0§T1§y2§U3§i4', [('SECRET', 'gh§p_§Q7§w8§E9§r0§T1§y2§U3§i4§O5§p6§Q7§w8§E9§r0§T1§y2§U3§i4')]),
    ('x§oxb TP', 'xo§xb§-1§23§45§67§89§0-§12§34§56§78§90§12§3-§Q7§w8§E9§r0§T1§y2§U3§i4§O5§p6§Q7§w8', [('SECRET', 'xo§xb§-1§23§45§67§89§0-§12§34§56§78§90§12§3-§Q7§w8§E9§r0§T1§y2§U3§i4§O5§p6§Q7§w8')]),
    ('label+random after value word', 'p§assword: id§en§ti§fi§er and the t§oken is Kx7Qp2Zr9Lm4Wn', [('SECRET', 'id§en§ti§fi§er')]),
    ('email freemail', 'ko§nt§ak§t@§gm§x-§be§is§pi§el§.d§e', [('EMAIL', 'ko§nt§ak§t@§gm§x-§be§is§pi§el§.d§e')]),
    ('sql3', "CREATE USER app WITH P§ASSWORD 'Kx§7Q§p2§Zr§9L§m4§Wn';", [('SECRET', 'Kx§7Q§p2§Zr§9L§m4§Wn')]),
    ('TP aig mail', 'Maintainer: ma§x.§mu§st§er§@f§ir§ma§-x§yz§.d§e\n', [('EMAIL', 'ma§x.§mu§st§er§@f§ir§ma§-x§yz§.d§e')]),
    ('TP aig ttl s§ecret', 'REFRESH_T§OKEN = Kx§7Q§p2§Zr§9L§m4§Wn\n', [('SECRET', 'Kx§7Q§p2§Zr§9L§m4§Wn')]),
    ('TP aig star in value', 'k§ennwort: 4C§X!§Dk§Q1§ya§*U§T-§Ci§$\n', [('SECRET', '4C§X!§Dk§Q1§ya§*U§T-§Ci§$')]),
]
